# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bcrypt', '~> 3.1.7'
gem 'jwt'
gem 'mysql2'
gem 'puma', '~> 3.7'
gem 'rack-cors'
gem 'rails', '~> 5.1.7'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'fablicop'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
