require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/task_labels", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TaskLabel. As you add validations to TaskLabel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TaskLabel.create! valid_attributes
      get task_labels_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      task_label = TaskLabel.create! valid_attributes
      get task_label_url(task_label)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_task_label_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      task_label = TaskLabel.create! valid_attributes
      get edit_task_label_url(task_label)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TaskLabel" do
        expect {
          post task_labels_url, params: { task_label: valid_attributes }
        }.to change(TaskLabel, :count).by(1)
      end

      it "redirects to the created task_label" do
        post task_labels_url, params: { task_label: valid_attributes }
        expect(response).to redirect_to(task_label_url(TaskLabel.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TaskLabel" do
        expect {
          post task_labels_url, params: { task_label: invalid_attributes }
        }.to change(TaskLabel, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post task_labels_url, params: { task_label: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested task_label" do
        task_label = TaskLabel.create! valid_attributes
        patch task_label_url(task_label), params: { task_label: new_attributes }
        task_label.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the task_label" do
        task_label = TaskLabel.create! valid_attributes
        patch task_label_url(task_label), params: { task_label: new_attributes }
        task_label.reload
        expect(response).to redirect_to(task_label_url(task_label))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        task_label = TaskLabel.create! valid_attributes
        patch task_label_url(task_label), params: { task_label: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested task_label" do
      task_label = TaskLabel.create! valid_attributes
      expect {
        delete task_label_url(task_label)
      }.to change(TaskLabel, :count).by(-1)
    end

    it "redirects to the task_labels list" do
      task_label = TaskLabel.create! valid_attributes
      delete task_label_url(task_label)
      expect(response).to redirect_to(task_labels_url)
    end
  end
end
