# frozen_string_literal: true

source 'https://rubygems.org'

gem 'mysql2'
gem 'puma', '~> 3.0'
gem 'rack-cors'
gem 'rails', '~> 5.1.0'
gem 'validates_timeliness'
gem 'jwt'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'fablicop'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
  gem 'sqlite3', '~> 1.3.13'
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
