inherit_gem:
  fablicop:
    - "config/.base_rubocop.yml"

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'
RSpec/AnyInstance:
  Exclude:
    - 'spec/**/*'
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleExpectations:
  Max: 10
RSpec/MultipleMemoizedHelpers:
  Max: 10
RSpec/Rails/AvoidSetupHook:
  Exclude:
    - 'test/**/*'
