inherit_gem:
  fablicop:
    - "config/.base_rubocop.yml"
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
# https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/MultipleExpectations
RSpec/MultipleExpectations:
  Max: 2

RSpec/NestedGroups:
  Max: 5

# https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FilePath
# RSpec::FilePath: 
#   SpecSuffixOnly: true
