require:
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  fablicop:
    - "config/.base_rubocop.yml"

AllCops:
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "db/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"
    - "app/channels/**/*"
    - "config/environments/**"
    - "config/initializers/**"
    - "config/environment.rb"
    - "config/boot.rb"
    - "config/puma.rb"
    - "config/spring.rb"
    - "config/application.rb"
    - "Rakefile"
    - "app/controllers/application_controller.rb"
    - "config.ru"
    - "app/models/application_record.rb"
    - "app/helpers/application_helper.rb"

Style/SymbolArray:
  EnforcedStyle: brackets
