# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fb305ba29509303b9c3b3b3f1691e0cc5580d922980318ec0f6cad3513c974cf0bd7ac2bce76b306f8834252a1555ae7619b62965e13824ff1471ee78835870

test:
  secret_key_base: 9cf1b020dae53f6e63fd040decc114944398f3d4e5ed07f925400cb1223bc359eab77fb35e661a9a94fb4011a1878c90c180e841e597fb84414c9d0bdc350c2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
